### ISSUE TITLE
Proposal for unknown key error

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#100]
There are realistically a few cases when unknown key errors occurs: 
- A fully deprecated variable.
- Depending on the implementation, a variable that is references in other variables. 
- Since json doesn't support comments, one might add a variable as comment. 

The other possible scenario is that a user made a typo with a specific variable. As the possibilities are finite, I think a typo can be detected, flagging an error before running the flow.

**Comment by donn** [comment]
Agreed.
