### ISSUE TITLE
LVS failures when more than two pins are connected to the same net

### ISSUE THREAD

**Issue by urish** [efabless/openlane2#111]
Tested with latest openlane2 (tag 2.0.0a47). 

Seems like there are two issues:
1. Spice extraction ignores nets with more than two pins. 
2. `Checker.LVS` code doesn't handle nets with more than two pins correctly.

The first item can be solved by adding by adding: `ext2spice short resistor` after this following line: https://github.com/efabless/openlane2/blob/9dfa57cac6bb3275dcc1b21d1eb4fab8396cd1a5/openlane/scripts/magic/extract_spice.tcl#L40

After I tried this solution locally, I got netgen to pass happily with:

```
Final result:
Circuits match uniquely.
```

However, Checker.LVS still fails despite netgen being happy:

```
─────────────────────────────────────────────────── Layout vs. Schematic Error Checker ───────────────────────────────────────────────────
[22:35:09] ❌  215 LVS errors found. - deferred                                                                              checker.py:70
           ❌  The following deferred step errors have been encountered:                                                 sequential.py:188
           ❌  215 LVS errors found.                                                                                     sequential.py:190
Traceback (most recent call last):
  File "/home/uri/p/tinytapeout-04/tt-multiplexer/ol2/tt_top/build.py", line 188, in <module>
    flow.start()
  File "/nix/store/kbkgfnnwxlhvldgmy3qn8xhkiavpl3ih-python3.10-openlane/lib/python3.10/site-packages/openlane/flows/flow.py", line 450, in
start
    final_state, step_objects = self.run(
  File "/nix/store/kbkgfnnwxlhvldgmy3qn8xhkiavpl3ih-python3.10-openlane/lib/python3.10/site-packages/openlane/flows/sequential.py", line 
191, in run
    raise FlowError("One or more deferred errors were encountered.")
```

Here is the netgen output before applying the `ext2spice short resistor` fix, where you could see netgen failing:

[before-netgen-resistors.zip](https://github.com/efabless/openlane2/files/11971742/before-netgen-resistors.zip)

And this is the netgen output after applying the `ext2spice short resistor` fix, where you could see netgen passing (but the checker-lvs fails):

[with-extract-resistors.zip](https://github.com/efabless/openlane2/files/11971748/with-extract-resistors.zip)

Happy to provide more information if needed.

**Comment by donn** [comment]
Could you kindly include the contents of these two files?

1. `/home/uri/p/tinytapeout-04/tt-multiplexer/ol2/tt_top/runs/RUN_2023-07-06_22-26-27/30-magic-spiceextraction/user_project_wrapper.spice`
2. `/home/uri/p/tinytapeout-04/tt-multiplexer/ol2/tt_top/runs/RUN_2023-07-06_22-26-27/15-openroad-detailedrouting/user_project_wrapper.pnl.v`

**Comment by donn** [comment]
For context, I'm noticing the pin lists in the LVS text report and the JSON report are quite different:

![Screenshot at 2023-07-10 17:55:12](https://github.com/efabless/openlane2/assets/12652988/b3456633-cb71-4487-91d8-ab1c9fe825c0)

![Screenshot at 2023-07-10 17:55:40](https://github.com/efabless/openlane2/assets/12652988/f2351bd1-7b28-4811-8e10-109cce5fb670)
![Screenshot at 2023-07-10 17:55:46](https://github.com/efabless/openlane2/assets/12652988/791b2b45-b4b8-4727-929b-ba680650684c)

The JSON report is basically fine for the first three, then it breaks. OpenLane parses the JSON report, so that's why it's reporting mismatches. I'd need to create a reproducible before reporting it as a netgen bug, however.

**Comment by urish** [comment]
> Could you kindly include the contents of these two files?

Sure, here they are:

[pnl_and_spice.zip](https://github.com/efabless/openlane2/files/12004833/pnl_and_spice.zip)

**Comment by donn** [comment]
Tracking in https://github.com/RTimothyEdwards/netgen/issues/78...

**Comment by urish** [comment]
Tested and confirm it's working well now:

![image](https://github.com/efabless/openlane2/assets/892318/59f14219-2ea7-4d30-aaa9-797ef678c1ee)

Thanks for fixing this so quickly!
