### ISSUE TITLE
`--dockerized` behvaior is not fully documented

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#143]
Using `--dockerized` as the last argument, launches a docker shell. This is not documented anywhere. Yes it is stated that it should precede other arguments but OpenLane accepts it when it doesn't. Furthermore, I believe this behavior is too magical.

**Comment by donn** [comment]
I don't disagree but I really have no better way of doing it. If you can figure out something better that works with our existing CLI parser, do give it a shot.
