### ISSUE TITLE
Migrating FP_PDN_MACRO_HOOKS

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#145]
`"PDN_MACRO_CONNECTIONS": "mprj vccd1 vssd1 vccd1 vssd1"` will generate an error mid flow. The error message is not very useful. The fix is to make it `"PDN_MACRO_CONNECTIONS": ["mprj vccd1 vssd1 vccd1 vssd1"]`

**Comment by donn** [comment]
Just so I don't forget: this will apply only to the migration, FP_PDN_MACRO_HOOKS. If you use the new name and insist on providing a string, I can only do so much.
