### ISSUE TITLE
There is no PDN configuration variables documentation in the floorplan section

### ISSUE THREAD

**Issue by mo-hosni** [efabless/openlane2#167]
There is no PDN configuration variables documentation in the floorplan section

**Comment by donn** [comment]
Yes, that would be because it's in the PDN section??????

**Comment by mo-hosni** [comment]
I cannot see a PDN section here: https://openlane2.readthedocs.io/en/latest/usage/hardening_macros.html
The PDN variables exist only in the PDK variables list here: https://openlane2.readthedocs.io/en/latest/reference/common_pdk_vars.html
which is a bit annoying because those should be modified for every macro. I know the default value should be different from one PDK to another. But I think those are very common variables that should be added to the "hardening macros" guide. Also, VPITCH and HPITCH are not in the PDK variables list and those are the 2 most important variables.
