### ISSUE TITLE
Detailed Placement padding

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#171]
The equivalent of https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/openroad/common/dpl_cell_pad.tcl should exist in openlane2. The reason behind is that there are multiple steps that insert cells such as resizer and heuristic antenna diode insertion. These steps need to obey padding rules set for the whole flow. Otherwise it can trigger errors such as the following https://github.com/efabless/openlane2/issues/168.

**Comment by donn** [comment]
Not entirely sure what you mean. That script exists. Furthermore, detailed placement is never performed without this script being sourced as unlike in OpenLane 1, all `detailed_placement` invocations happen in `dpl.tcl`.
