### ISSUE TITLE
Error with Package

### ISSUE THREAD

**Issue by Ram-Ganesh** [efabless/openlane2#199]
### Description

when i am executing the flow.tcl , getting the error like package json is required.

can anyone help me on this?

### Expected Behavior

want to execute the flow.tcl of spm block 

### Environment report

```sh
can't find package json
    while executing
"package require json"
    (file "/home/ram/OpenLane/scripts/tcl_commands/all.tcl" line 15)
    invoked from within
"source /home/ram/OpenLane/scripts/tcl_commands/all.tcl"
    ("package ifneeded openlane 0.9" script)
    invoked from within
"package require openlane"
    (file "./flow.tcl" line 25)
```

### Reproduction material

can't find package json
    while executing
"package require json"
    (file "/home/ram/OpenLane/scripts/tcl_commands/all.tcl" line 15)
    invoked from within
"source /home/ram/OpenLane/scripts/tcl_commands/all.tcl"
    ("package ifneeded openlane 0.9" script)
    invoked from within
"package require openlane"
    (file "./flow.tcl" line 25)

### Relevant log output

```sh
can't find package json
    while executing
"package require json"
    (file "/home/ram/OpenLane/scripts/tcl_commands/all.tcl" line 15)
    invoked from within
"source /home/ram/OpenLane/scripts/tcl_commands/all.tcl"
    ("package ifneeded openlane 0.9" script)
    invoked from within
"package require openlane"
    (file "./flow.tcl" line 25)
```

**Comment by donn** [comment]
1. This is the OpenLane 2.0.0 beta repo. There is no `flow.tcl`. You're looking for https://github.com/The-OpenROAD-Project/OpenLane.
2. Kindly follow the instructions in https://openlane.readthedocs.io/en/latest/getting_started/installation/installation_ubuntu.html accurately. You seem to have skipped the Docker mount steps.
