### ISSUE TITLE
Clean Up Documentation

### ISSUE THREAD

**Issue by donn** [efabless/openlane2#220]
### Description

The documentation currently:
* Says "OpenLane" unqualified (should mention OpenLane version 2 beta)
* Makes reference to tools or utilities removed in OpenLane 2.0+ (spef extractor, CVC…)
* Does not properly link to OpenLane 2
  * There should be a repository link
  * The edit button (top right) links to OpenLane 1 (!!)

### Proposal

Fix these

**Comment by kareefardi** [comment]
Fixed in upstream
