### ISSUE TITLE
Allow tristate cells in synth checks

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#285]
### Description

Currently we allow tristate cells generated by yosys which marked with `tribuf`. However if we have a hand instantiated tristate cell it would fail.  

### Proposal

OpenLane has a variable for a prefix (set by the PDK) that filters out these cells. We can use that here too.

**Comment by donn** [comment]
After internal discussion, we've come to the conclusion that we should just match OpenLane 1 for now.
