### ISSUE TITLE
Feature Parity with OpenLane 1

### ISSUE THREAD

**Issue by donn** [efabless/openlane2#3]
- [x] Macro Flows
- [x] LVS/Spice
- [x] LEC
- [x] Antenna Checker
- [x] KLayout Streamout
- [x] KLayout DRC
- [ ] Padframe Gen
- [ ] `run_designs` alternative
- [x] Docker support

## New PRs
- [x] https://github.com/The-OpenROAD-Project/OpenLane/pull/1687
- [x] https://github.com/The-OpenROAD-Project/OpenLane/pull/1675
- [x] https://github.com/The-OpenROAD-Project/OpenLane/pull/1715

**Comment by kareefardi** [comment]
Updated main comment with  
```
Additional checks in QUIT_ON_SYNTH_CHECK￼
Hierarchical sta
```

**Comment by donn** [comment]
GF180 support blocked on The-OpenROAD-Project/OpenROAD#3155
