### ISSUE TITLE
 OpenIKLayout DRC report

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#322]
### Description

OpenInKLayout should attempt to load DRC error reports generated by a step. It will be more convenient and ensures consistent usage of the CLI for displaying the layout at any step. 

### Proposal

Maybe add a CLI option or have the flow detect non empty DRC report file generated by the step it is attempting to load.

**Comment by donn** [comment]
There's no way to do this without violating OpenLane 2's step strictures… https://openlane2.readthedocs.io/en/latest/reference/architecture.html#steps

**Comment by kareefardi** [comment]
@donn We may want to keep the issue open as a potential enhancement in future releases.
