### ISSUE TITLE
Deep instances

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#358]
### Description

In a config, a user should be able to specify an instance of MACRO, deeper in the hierarchy, inside another instance of a macro. At the moment, any instance must have a location entry, while deeper instances are already placed. 

### Proposal

Remove hard requirement on location for instances.

**Comment by donn** [comment]
I'm not sure what this achieves exactly. If a macro is placed within another macro, it should be abstracted by said Macro. This seems like a workaround for macros that were hardened improperly.

**Comment by kareefardi** [comment]
> I'm not sure what this achieves exactly. If a macro is placed within another macro, it should be abstracted by said Macro. This seems like a workaround for macros that were hardened improperly.

This achieves more comprehensive `STA`.

**Comment by kareefardi** [comment]
Fixed by https://github.com/efabless/openlane2/pull/359
