### ISSUE TITLE
Running smoke test as the very first command fails because the PDK_ROOT dir is created as root:root

### ISSUE THREAD

**Issue by smunaut** [efabless/openlane2#41]
When launching it from scratch on a brand new system, the PDK_ROOT dir not created yet, it will be created but as belonging to root:root  event though I'm running openlane as normal user (not even sure how/why ... I'm assuming through some docker magic or something), and then them volare try to do the actual install ... wel it can't write to it as normal user so it fails with a permission error.

**Comment by donn** [comment]
Are you using `--dockerized`, perchance?
