### ISSUE TITLE
Please update `rich` and `klayout` dependencies

### ISSUE THREAD

**Issue by hpretl** [efabless/openlane2#494]
### Description

Hi @donn could you please update the `rich` dependency to be compatible with `cace` from @mole99:

<img width="355" alt="image" src="https://github.com/efabless/openlane2/assets/57392031/622ef31c-5b8e-4254-ab95-e8376483e84d">

### Proposal

Upgrading to rich < 14 would be ideal.

**Comment by donn** [comment]
Looking into it

**Comment by hpretl** [comment]
BTW, when you are looking at this: Bumping KLayout to <=0.92.2 (or at least 0.91.1) would also be quite helpful! :-)

**Comment by kareefardi** [comment]
Rich issue addressed by https://github.com/efabless/openlane2/pull/495

**Comment by hpretl** [comment]
Thank you, the issue regarding `rich` looks solved, `openlane` and `cace` can now coexist, thanks!

Unfortunately, there is still an incompatibility with `kfactory` (an important piece of `gdsfactory`) on `klayout`, please see here:

```
33.63 ERROR: Cannot install kfactory[git,ipy]==0.17.4 and openlane==2.0.10 because these package versions have conflicting dependencies.
33.63
33.63 The conflict is caused by:
33.63     openlane 2.0.10 depends on klayout<0.29.0 and >=0.28.17.post1
33.63     kfactory[git,ipy] 0.17.4 depends on klayout>=0.29.1
```

**Comment by hpretl** [comment]
@donn @kareefardi Would an update of the dependency to `klayout<=0.29.1` work?

**Comment by hpretl** [comment]
I tested klayout 0.29.2, and it runs fine on the smoke test.

**Comment by hpretl** [comment]
See https://github.com/efabless/openlane2/pull/496

**Comment by donn** [comment]
Done in dev
