### ISSUE TITLE
Hierarchical STA, hierarchical LVS, and routing obstructions.

### ISSUE THREAD

**Issue by mo-hosni** [efabless/openlane2#5]
The following features would be very useful and can be added to openlane2.
- [ ] **Hierarchical STA**: 
Instead of treating macros as black-box instances with liberty files in STA, gate-level netlists and spef files for the macros may be used. This [script](https://github.com/efabless/caravel/blob/main/scripts/spef_mapping.tcl) might be useful.
- [ ]  **Hierarchical LVS**: 
Instead of treating macros as black-box instances in GDS LVS, gate-level netlists for the macros may be used. This [script](https://github.com/efabless/caravel/blob/main/scripts/run_caravan_lvs_3.sh) might be usefull.
- [ ]  **PDN and Placement Obstructions**: 
Adding obstructions before PDN generation and before placement is useful in many cases.

**Comment by donn** [comment]
To shed some light on why hierarchical STA specifically is taking so long: This is coming along with a set of refactors to do the following:

* Explicitly specified timing corners as a combination of ((I)nterconnect, Transistor (P)roccess, (V)oltage, and (T)emperature)
* The ability of the `State` object to incorporate N-deep dictionaries for particular design formats to support the above (with validation)
* The ability of the `Config` object to incorporate dictionaries (for PDK objects) and complex data structures (for things like Macro definitions), all with desarialization and validation
* A rewrite of various steps to:
  * Properly match timing corners with liberty and/or SPEF files
  * A reconfiguration of the OpenROAD.STA class structure

**Comment by donn** [comment]
Given that hierarchical STA is now added, I will close this issue and open two new ones for the two other features.
