### ISSUE TITLE
Allow Docker drop-in alternatives, such as podman

### ISSUE THREAD

**Issue by maxrdz** [efabless/openlane2#510]
### Description

I have a Docker drop-in alternative installed on my system, podman, which is a very popular choice. It seems that when the `--dockerized` argument is passed, it searches explicitly for a `docker` binary. Could OpenLANE search for alternatives as well? Or maybe configurable?

Aliasing `docker` as `podman` doesn't seem to work, since I assume it looks for the binary in the filesystem, and then executes it, instead of going through the shell. So, currently the only work around on a Linux environment is to create a symlink to the `podman` binary with the name `docker` in the system bin.

**Comment by donn** [comment]
`export OPENLANE_CONTAINER_ENGINE=podman` would do it. I use nerdctl personally, albeit with a symlink instead of an alias. 🙂

**Comment by donn** [comment]
Did this work for you, Max?

**Comment by maxrdz** [comment]
> Did this work for you, Max?

Yes, it did. Thank you for the prompt response, and sorry for my late response. 😛
