### ISSUE TITLE
Direct `debug` tools using the CLI

### ISSUE THREAD

**Issue by daquintero** [efabless/openlane2#603]
### Description

Hello, hope you all are doing great, long time!

Thought a CLI `openlane --logger`  or `openlane --debug` CLI addition could be really good to debug environments and PDKs configurations when it is not possible to interact with a development openlane. Mainly it would print all the relevant configuration information maybe even in a `openlane --dry-run` design run.

So it could help mainly to solve PDK configuration problems between `volare` and `openlane` in CLI design usage. I know there's already some logging functionality on the python but maybe I've missed it on the CLI (although I had a decent search through docs and the API as I was able to).

```
 File "/nix/store/9jb8wsk32ny2yy5ghcaq3y7mbmmavi2c-python3.11-openlane/lib/python3.11/site-packages/openlane/common/tcl.py", line 78, in _eval_env
    interpreter.eval(tcl_in)
_tkinter.TclError: can't read "::env(STD_CELL_LIBRARY_OPT)": no such element in array

  File "/nix/store/9jb8wsk32ny2yy5ghcaq3y7mbmmavi2c-python3.11-openlane/lib/python3.11/site-packages/openlane/common/tcl.py", line 78, in _eval_env
    interpreter.eval(tcl_in)
_tkinter.TclError: can't read "::env(STD_CELL_LIBRARY)": no such element in array
```

Maybe even a CLI option helped clarify what are the options or configuration settings missing that'd also be pretty incredible.

Just thought would be a nice improvement! If I get time at some point happy to contribute, but thought to propose

**Comment by donn** [comment]
Hiya Dario, hope you're doing well.

There's `--log-level DEBUG`, however, there aren't as many debug messages as we'd like. That's an area for easy enhancement though.

**Comment by daquintero** [comment]
:raised_hands: :raised_hands: :raised_hands:  Thank you very good sir! 
Yes, I've just also noticed it in the CLI output options actually, I must have missed it before sorry actually. It's really useful so thanks a lot for this and all you have been doing. Hopefully we get to coincide again and catch up at some point!
