### ISSUE TITLE
Expressions don't work in python dict config

### ISSUE THREAD

**Issue by smunaut** [efabless/openlane2#61]
When using `init_with_config` using a python dict and not a json file, then `_load_dict` ends up being called without `resolve_json=True` argument and the user has no way to set it, which makes expressions don't work.

**Comment by donn** [comment]
This is by design- the intent is, if you're writing your dict in Python, there's no need for the expression engine. I'm open to discussing this though.

**Comment by smunaut** [comment]
So my use case for it here is when building the top level. Some of the variable are provided from the default project as "Don't touch theses" (so that the result is "caravel compatible") and so I load those from a `.json` file and then add some other custom/dynamic config (like macro and such) programatically.

But those "don't touch" config do include expressions ...

**Comment by donn** [comment]
That does make sense.

I'll look into it.

**Comment by donn** [comment]
They should work now- but I'll still go ahead and advise against it in scenarios other than precisely this.
