### ISSUE TITLE
Generate `tcl_reproductible` for steps that don't crash

### ISSUE THREAD

**Issue by smunaut** [efabless/openlane2#81]
It would be nice to be able to generate the same kind of `tcl_reproductible` directory even for steps that don't crash outright because it could still be that something goes wrong there.

For instance here I'm having an issue that crashes in detailled routing but it seems like the issue might be earlier in globalrouting that the DB gets corrupted or something even though it doesn't crash there. So it'd be nice if I could send the same kind of reproductible build artefact for the globalrouting step.

**Comment by donn** [comment]
Added in beta 3: just navigate to a step directory and invoke `python3 -m openlane.steps create-reproducible -d .`
