### ISSUE TITLE
Yosys config params

### ISSUE THREAD

**Issue by mohamedleithy** [efabless/openlane2#89]
`ERROR: Module \sky130_fd_sc_hd__dlclkp_1 referenced in module \BYTE' in cell  \genblk1.CG is not part of the design` while having `"SYNTH_ELABORATE_ONLY": "1"` and `"SYNTH_READ_BLACKBOX_LIB": "1"`. 

[tcl_reproducible.zip](https://github.com/efabless/openlane2/files/11635639/tcl_reproducible.zip)

**Comment by smunaut** [comment]
(1) See #59 ... that config doesn't do anything ATM.
(2) `sky130_fd_sc_hd__dlclkp_1` is in the PDK `no_synth.cells` list end ends up exclude from being passed to yosys.
You can use `SYNTH_EXCLUSION_CELL_LIST` to pass a custom (possibly empty) file with list of excluded cells.

**Comment by mohamedleithy** [comment]
Thank you!
