### ISSUE TITLE
PDN_MACRO_CONNECTIONS doesn't work. Value gets mangled.

### ISSUE THREAD

**Issue by smunaut** [efabless/openlane2#90]
The value that gets to the actual TCL script is mangled and not the actual string specified ...
This is what I put in my dict :
```python
              "PDN_MACRO_CONNECTIONS": [
                       "top_I.*tt_um_I vccd1 vssd1 vccd1 vssd1",
               ],
```
But then because there is only one line (I guess) or because of spaces, it get split into a lits of words and then for some reason the first one end up with single quotes around it in the TCL which completely screws it  and doesn't match ...

**Comment by donn** [comment]
It's joined with `shlex` to ensure that spaces and such are properly escaped- that said, the splitting is a bug.

However, as far as I can see, testing shows that it does match...

**Comment by smunaut** [comment]
That still doesn't work.

To debug, in `set_global_connections.tcl`, I added `puts "|$pdn_hook|$instance_name|"` in the `for` loop.
And this is what gets printed in the logs :

```
|'top_I.*tt_um_I vccd1 vssd1 vccd1 vssd1'|'top_I.*tt_um_I|
```

And you can notice there are extraneous `'` at beginning and end. And the one at the beginning ends up in the `instance_name` and the final one ends up in `ground_pin` ....

**Comment by donn** [comment]
Should be fixed now- sorry for the long delay.

Have I mentioned I hate Tcl?

**Comment by smunaut** [comment]
:tada:   I confirm this fixed the issue for me.
